# 数据清洗

In [ ]:
import pandas as pd

In [2]:
# 读取 pokemon151_v3.csv 数据集
pokemon_path = "../data/raw/pokemon151_v3.csv"
pokemon_df = pd.read_csv(pokemon_path, encoding="utf-8")
pokemon_df.head()

,pokemon_id,name_en,name_cn,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,evolution_id,evolution_stage,remaining_evolutions,pre_evolution_id,post_evolution_id,evolution_level,latest_generation
0,1,Bulbasaur,妙蛙种子,Grass,Poison,45,49,49,65,65,45,1,1,2,NaN,2,NaN,9
1,2,Ivysaur,妙蛙草,Grass,Poison,60,62,63,80,80,60,1,2,1,1.0,3,16,9
2,3,Venusaur,妙蛙花,Grass,Poison,80,82,83,100,100,80,1,3,0,2.0,NaN,32,9
3,4,Charmander,小火龙,Fire,NaN,39,52,43,60,50,65,2,1,2,NaN,5,NaN,9
4,5,Charmeleon,火恐龙,Fire,NaN,58,64,58,80,65,80,2,2,1,4.0,6,16,9

In [3]:
# 读取 move_v2.csv 数据集
move_path = "../data/raw/move_v2.csv"
move_df = pd.read_csv(move_path, encoding="utf-8")
move_df.head()

,move_id,name_en,name_cn,type,category,power,accuracy,pp,effect
0,1,"10,000,000 Volt Thunderbolt",千万伏特,Electric,2,195,—,1,"10,000,000 Volt Thunderbolt is an Electric typ..."
1,2,Absorb,吸取,Grass,2,20,100,25,Absorb deals damage and the user will recover ...
2,3,Accelerock,冲岩,Rock,1,40,100,20,Accelerock deals damage and has high priority....
3,4,Acid,溶解液,Poison,2,40,100,30,Acid deals damage and has a 10% chance of lowe...
4,5,Acid Armor,溶化,Poison,3,—,—,20,Acid Armor raises the user's Defense by two st...

In [4]:
# 读取 learn_v2.csv 数据集
learn_path = "../data/raw/learn_v2.csv"
learn_df = pd.read_csv(learn_path, encoding="utf-8")
learn_df.head()

,learn_id,pokemon_id,move_id,pokemon_name_en,move_name_en,gen,method,method_transfer,learn_level
0,1,1,352,Bulbasaur,Growl,9,level_up,NaN,1
1,2,1,830,Bulbasaur,Tackle,9,level_up,NaN,1
2,3,1,897,Bulbasaur,Vine Whip,9,level_up,NaN,3
3,4,1,353,Bulbasaur,Growth,9,level_up,NaN,6
4,5,1,451,Bulbasaur,Leech Seed,9,level_up,NaN,9

## 处理 move 表

In [5]:
# 将 move_df 中的 category 列中的数值替换为对应的字符串
move_df.loc[move_df["category"] == '1', "category"] = "physical"
move_df.loc[move_df["category"] == '2', "category"] = "special"
move_df.loc[move_df["category"] == '3', "category"] = "status"
move_df.head()

,move_id,name_en,name_cn,type,category,power,accuracy,pp,effect
0,1,"10,000,000 Volt Thunderbolt",千万伏特,Electric,special,195,—,1,"10,000,000 Volt Thunderbolt is an Electric typ..."
1,2,Absorb,吸取,Grass,special,20,100,25,Absorb deals damage and the user will recover ...
2,3,Accelerock,冲岩,Rock,physical,40,100,20,Accelerock deals damage and has high priority....
3,4,Acid,溶解液,Poison,special,40,100,30,Acid deals damage and has a 10% chance of lowe...
4,5,Acid Armor,溶化,Poison,status,—,—,20,Acid Armor raises the user's Defense by two st...

## 处理 learn 表

### 检查 learn.csv 中的重复行

In [6]:
# 以pokemon_id, move_id, method为依据，检查重复行总数
cols_v1 = ["pokemon_id", "move_id", "method"]

dup_rows_v1 = learn_df[learn_df.duplicated(subset=cols_v1, keep=False)].sort_values(cols_v1)
print(f"重复行总数: {dup_rows_v1.shape[0]}")
dup_rows_v1

重复行总数: 5246

,learn_id,pokemon_id,move_id,pokemon_name_en,move_name_en,gen,method,method_transfer,learn_level
22,23,1,7,Bulbasaur,Acid Spray,9,TM,NaN,0
84,85,1,7,Bulbasaur,Acid Spray,9,TM,NaN,0
31,32,1,75,Bulbasaur,Body Slam,9,TM,NaN,0
73,74,1,75,Bulbasaur,Body Slam,9,TM,NaN,0
29,30,1,98,Bulbasaur,Bullet Seed,9,TM,NaN,0
...,...,...,...,...,...,...,...,...,...
15108,15109,150,872,Mewtwo,Trailblaze,9,TM,NaN,0
15001,15002,150,919,Mewtwo,Will-O-Wisp,9,TM,NaN,0
15082,15083,150,919,Mewtwo,Will-O-Wisp,9,TM,NaN,0
14976,14977,150,932,Mewtwo,Zen Headbutt,9,TM,NaN,0
15083,15084,150,932,Mewtwo,Zen Headbutt,9,TM,NaN,0

In [7]:
before = len(learn_df)
learn_df_v1 = learn_df.drop_duplicates(subset=cols_v1, keep="first").reset_index(drop=True)
after = len(learn_df_v1)
print(f"保留第一条 — 删除: {before - after} 行 （前: {before}, 后: {after}）")
learn_df_v1.head()

保留第一条 — 删除: 2644 行 （前: 15585, 后: 12941）

,learn_id,pokemon_id,move_id,pokemon_name_en,move_name_en,gen,method,method_transfer,learn_level
0,1,1,352,Bulbasaur,Growl,9,level_up,NaN,1
1,2,1,830,Bulbasaur,Tackle,9,level_up,NaN,1
2,3,1,897,Bulbasaur,Vine Whip,9,level_up,NaN,3
3,4,1,353,Bulbasaur,Growth,9,level_up,NaN,6
4,5,1,451,Bulbasaur,Leech Seed,9,level_up,NaN,9

### 检查发现 method_transfer 列意义不大且容易出问题，删去此列

In [8]:
# 显示 method_transfer 列值不为 NAN 的所有行
filtered_rows = learn_df_v1[learn_df_v1["method_transfer"].notnull()]
print(f"method_transfer 不为 NAN 的行数: {filtered_rows.shape[0]}")
filtered_rows

method_transfer 不为 NAN 的行数: 91

,learn_id,pokemon_id,move_id,pokemon_name_en,move_name_en,gen,method,method_transfer,learn_level
1805,2381,25,198,Pikachu,Draining Kiss,9,transfer,transfer,0
1891,2502,26,198,Raichu,Draining Kiss,9,transfer,transfer,0
1892,2503,26,210,Raichu,Eerie Impulse,9,transfer,TR,0
1993,2630,28,69,Sandslash,Blizzard,9,transfer,transfer,0
1994,2631,28,162,Sandslash,Defense Curl,9,transfer,transfer,0
...,...,...,...,...,...,...,...,...,...
11038,13296,136,835,Flareon,Take Down,9,transfer,transfer,0
11039,13297,136,921,Flareon,Wish,9,transfer,transfer,0
12249,14791,149,254,Dragonite,Fire Punch,9,transfer,transfer,0
12250,14792,149,858,Dragonite,Thunder Punch,9,transfer,TR,0
12251,14793,149,920,Dragonite,Wing Attack,9,transfer,transfer,0

In [9]:
learn_df_v2 = learn_df_v1.drop(columns=["method_transfer"])
learn_df_v2.head()

,learn_id,pokemon_id,move_id,pokemon_name_en,move_name_en,gen,method,learn_level
0,1,1,352,Bulbasaur,Growl,9,level_up,1
1,2,1,830,Bulbasaur,Tackle,9,level_up,1
2,3,1,897,Bulbasaur,Vine Whip,9,level_up,3
3,4,1,353,Bulbasaur,Growth,9,level_up,6
4,5,1,451,Bulbasaur,Leech Seed,9,level_up,9

### 更新 learn_id

In [ ]:
learn_df_v2["learn_id"] = range(1, len(learn_df_v2) + 1)
learn_df_v2

,learn_id,pokemon_id,move_id,pokemon_name_en,move_name_en,gen,method,learn_level
0,1,1,352,Bulbasaur,Growl,9,level_up,1
1,2,1,830,Bulbasaur,Tackle,9,level_up,1
2,3,1,897,Bulbasaur,Vine Whip,9,level_up,3
3,4,1,353,Bulbasaur,Growth,9,level_up,6
4,5,1,451,Bulbasaur,Leech Seed,9,level_up,9
...,...,...,...,...,...,...,...,...
12936,12937,151,365,Mew,Hard Press,9,TM,0
12937,12938,151,187,Mew,Dragon Cheer,9,TM,0
12938,12939,151,17,Mew,Alluring Voice,9,TM,0
12939,12940,151,622,Mew,Psychic Noise,9,TM,0
12940,12941,151,889,Mew,Upper Hand,9,TM,0

In [14]:
value = 1
pokemon_learn = learn_df_v2[learn_df_v2["pokemon_id"] == value]
print(f"id 为 {value} 的宝可梦的技能学习情况: {pokemon_learn.shape[0]}")
pokemon_learn

id 为 1 的宝可梦的技能学习情况: 61

,learn_id,pokemon_id,move_id,pokemon_name_en,move_name_en,gen,method,learn_level
0,1,1,352,Bulbasaur,Growl,9,level_up,1
1,2,1,830,Bulbasaur,Tackle,9,level_up,1
2,3,1,897,Bulbasaur,Vine Whip,9,level_up,3
3,4,1,353,Bulbasaur,Growth,9,level_up,6
4,5,1,451,Bulbasaur,Leech Seed,9,level_up,9
...,...,...,...,...,...,...,...,...
56,57,1,183,Bulbasaur,Double-Edge,9,level_up,45
57,58,1,457,Bulbasaur,Light Screen,9,TM,0
58,59,1,683,Bulbasaur,Safeguard,9,TM,0
59,60,1,925,Bulbasaur,Work Up,9,TM,0
60,61,1,583,Bulbasaur,Petal Dance,9,TM,0

## 处理 pokemon 表

### 更新 latest_generation

In [ ]:
# 计算每个 pokemon_id 的最大 gen
max_gen = learn_df.groupby("pokemon_id", as_index=False)["gen"].max()
max_gen.rename(columns={"gen": "latest_generation"}, inplace=True)

# 赋值到 pokemon_df
pokemon_df["latest_generation"] = pokemon_df["pokemon_id"].map(
    learn_df.groupby("pokemon_id")["gen"].max()
)
pokemon_df

,pokemon_id,name_en,name_cn,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,evolution_id,evolution_stage,remaining_evolutions,pre_evolution_id,post_evolution_id,evolution_level,latest_generation
0,1,Bulbasaur,妙蛙种子,Grass,Poison,45,49,49,65,65,45,1,1,2,NaN,2,NaN,9
1,2,Ivysaur,妙蛙草,Grass,Poison,60,62,63,80,80,60,1,2,1,1.0,3,16,9
2,3,Venusaur,妙蛙花,Grass,Poison,80,82,83,100,100,80,1,3,0,2.0,NaN,32,9
3,4,Charmander,小火龙,Fire,NaN,39,52,43,60,50,65,2,1,2,NaN,5,NaN,9
4,5,Charmeleon,火恐龙,Fire,NaN,58,64,58,80,65,80,2,2,1,4.0,6,16,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,Dratini,迷你龙,Dragon,NaN,41,64,45,50,50,50,76,1,2,NaN,148,NaN,9
147,148,Dragonair,哈克龙,Dragon,NaN,61,84,65,70,70,70,76,2,1,147.0,149,30,9
148,149,Dragonite,快龙,Dragon,Flying,91,134,95,100,100,80,76,3,0,148.0,NaN,55,9
149,150,Mewtwo,超梦,Psychic,NaN,106,110,90,154,90,130,77,1,0,NaN,NaN,NaN,9
150,151,Mew,梦幻,Psychic,NaN,100,100,100,100,100,100,78,1,0,NaN,NaN,NaN,9

## 导出清洗后的数据

In [15]:
data_path = "../data/processed/"
pokemon_df.to_csv(data_path + 'pokemon.csv', index=False, encoding='utf-8')
move_df.to_csv(data_path + 'move.csv', index=False, encoding='utf-8')
learn_df_v2.to_csv(data_path + 'learn.csv', index=False, encoding='utf-8')